export const PATTERN_SECTIONS = [
  { pattern: 4, title: 'Arcs',   subtitle: 'Concentric shapes and gradients' },
  { pattern: 0, title: 'Hills', subtitle: 'Smooth rolling hills and pine forests' },
  { pattern: 1, title: 'Waves',   subtitle: 'Fluid and organic curves' },
  { pattern: 3, title: 'Peaks', subtitle: 'Sharp and dramatic mountain peaks' },
  { pattern: 2, title: 'Dunes',   subtitle: 'Organic wind-swept sand dunes' },
  { pattern: 5, title: 'Scribbles', subtitle: 'Abstract freeform scribbles and lines' },
  { pattern: 8, title: 'Big Sur Waves', subtitle: 'macOS Big Sur style fluid colorful waves' },
  { pattern: 9, title: 'Monterey Silk', subtitle: 'macOS Monterey layered silk ribbons' },
  { pattern: 10, title: 'Ventura Petals', subtitle: 'macOS Ventura abstract layered petals' },
  { pattern: 11, title: 'Sonoma Topo', subtitle: 'macOS Sonoma organic contour waves' },
  { pattern: 12, title: 'Mesh Gradient', subtitle: 'Smooth color transitions and mesh blends' },
  { pattern: 13, title: 'Glass Bubbles', subtitle: 'Floating translucent bubbles with specular highlights' },
  { pattern: 14, title: 'Light Beams', subtitle: 'iOS sweeping neon light trails' },
  { pattern: 15, title: 'Origami Crystal', subtitle: 'Overlapping colorful faceted geometric triangles' },
  { pattern: 16, title: 'Minimalist Lines', subtitle: 'Sleek, elegant topographical line art' },
  { pattern: 17, title: 'Aurora Lights', subtitle: 'Layered glowing atmospheric light waves' },
  { pattern: 18, title: 'Cyber Grid', subtitle: 'Perspective digital wireframes and gridlines' },
  { pattern: 19, title: 'Liquid Marble', subtitle: 'Swirling fluid marble and concentric curves' }
];

export const wallpapers = [
  // ── Colinas (pattern 0) — seed 2718 ── Light
  { id: 'hills-fire',           name: 'Fire Hills',         pattern: 0, palette: 4,  seed: 2718, inverted: true },
  { id: 'hills-purple',         name: 'Purple Hills',         pattern: 0, palette: 5,  seed: 2718, inverted: true },
  { id: 'hills-toxic',          name: 'Toxic Hills',       pattern: 0, palette: 6,  seed: 2718, inverted: true },
  { id: 'hills-neon',           name: 'Neon Hills',         pattern: 0, palette: 8,  seed: 2718, inverted: true },
  { id: 'hills-cosmic',         name: 'Cosmic Hills',      pattern: 0, palette: 11, seed: 2718, inverted: true },
  { id: 'hills-blue',           name: 'Blue Hills',         pattern: 0, palette: 2,  seed: 2718, inverted: true },
  { id: 'hills-forest',         name: 'Forest Hills',     pattern: 0, palette: 10, seed: 2718, inverted: true },
  { id: 'hills-amber',          name: 'Amber Hills',        pattern: 0, palette: 7,  seed: 2718, inverted: true },
  { id: 'hills-solar',          name: 'Solar Hills',        pattern: 0, palette: 9,  seed: 2718, inverted: true },
  { id: 'hills-sunrise',        name: 'Sunrise Hills',    pattern: 0, palette: 3,  seed: 2718, inverted: true },
  { id: 'hills-charcoal',       name: 'Charcoal Hills',       pattern: 0, palette: 0,  seed: 2718, inverted: true },
  { id: 'hills-stone',          name: 'Stone Hills',        pattern: 0, palette: 1,  seed: 2718, inverted: true },
  { id: 'hills-ocean',          name: 'Ocean Hills',       pattern: 0, palette: 12, seed: 2718, inverted: true },
  { id: 'hills-blood',          name: 'Blood Hills',       pattern: 0, palette: 13, seed: 2718, inverted: true },
  { id: 'hills-sunset',         name: 'Sunset Hills',   pattern: 0, palette: 14, seed: 2718, inverted: true },
  { id: 'hills-emerald',        name: 'Emerald Hills',    pattern: 0, palette: 15, seed: 2718, inverted: true },
  { id: 'hills-cyberpunk',      name: 'Cyberpunk Hills',    pattern: 0, palette: 16, seed: 2718, inverted: true },
  { id: 'hills-sands',          name: 'Sands Hills',       pattern: 0, palette: 17, seed: 2718, inverted: true },
  { id: 'hills-lavender',       name: 'Lavender Hills',      pattern: 0, palette: 18, seed: 2718, inverted: true },
  { id: 'hills-gold',           name: 'Gold Hills',         pattern: 0, palette: 19, seed: 2718, inverted: true },
  { id: 'hills-mint',           name: 'Mint Hills',        pattern: 0, palette: 20, seed: 2718, inverted: true },
  { id: 'hills-cherry',         name: 'Cherry Hills',    pattern: 0, palette: 21, seed: 2718, inverted: true },
  { id: 'hills-volcano',        name: 'Volcano Hills',       pattern: 0, palette: 22, seed: 2718, inverted: true },
  { id: 'hills-indigo',         name: 'Indigo Hills',       pattern: 0, palette: 23, seed: 2718, inverted: true },
  // Dark
  { id: 'hills-fire-d',         name: 'Dark Fire Hills',         pattern: 0, palette: 4,  seed: 2718, inverted: false },
  { id: 'hills-purple-d',       name: 'Dark Purple Hills',         pattern: 0, palette: 5,  seed: 2718, inverted: false },
  { id: 'hills-toxic-d',        name: 'Dark Toxic Hills',       pattern: 0, palette: 6,  seed: 2718, inverted: false },
  { id: 'hills-neon-d',         name: 'Dark Neon Hills',         pattern: 0, palette: 8,  seed: 2718, inverted: false },
  { id: 'hills-cosmic-d',       name: 'Dark Cosmic Hills',      pattern: 0, palette: 11, seed: 2718, inverted: false },
  { id: 'hills-blue-d',         name: 'Dark Blue Hills',         pattern: 0, palette: 2,  seed: 2718, inverted: false },
  { id: 'hills-forest-d',       name: 'Dark Forest Hills',     pattern: 0, palette: 10, seed: 2718, inverted: false },
  { id: 'hills-amber-d',        name: 'Dark Amber Hills',        pattern: 0, palette: 7,  seed: 2718, inverted: false },
  { id: 'hills-solar-d',        name: 'Dark Solar Hills',        pattern: 0, palette: 9,  seed: 2718, inverted: false },
  { id: 'hills-sunrise-d',      name: 'Dark Sunrise Hills',    pattern: 0, palette: 3,  seed: 2718, inverted: false },
  { id: 'hills-charcoal-d',     name: 'Dark Charcoal Hills',       pattern: 0, palette: 0,  seed: 2718, inverted: false },
  { id: 'hills-stone-d',        name: 'Dark Stone Hills',        pattern: 0, palette: 1,  seed: 2718, inverted: false },
  { id: 'hills-ocean-d',        name: 'Dark Ocean Hills',       pattern: 0, palette: 12, seed: 2718, inverted: false },
  { id: 'hills-blood-d',        name: 'Dark Blood Hills',       pattern: 0, palette: 13, seed: 2718, inverted: false },
  { id: 'hills-sunset-d',       name: 'Dark Sunset Hills',   pattern: 0, palette: 14, seed: 2718, inverted: false },
  { id: 'hills-emerald-d',      name: 'Dark Emerald Hills',    pattern: 0, palette: 15, seed: 2718, inverted: false },
  { id: 'hills-cyberpunk-d',    name: 'Dark Cyberpunk Hills',    pattern: 0, palette: 16, seed: 2718, inverted: false },
  { id: 'hills-sands-d',        name: 'Dark Sands Hills',       pattern: 0, palette: 17, seed: 2718, inverted: false },
  { id: 'hills-lavender-d',     name: 'Dark Lavender Hills',      pattern: 0, palette: 18, seed: 2718, inverted: false },
  { id: 'hills-gold-d',         name: 'Dark Gold Hills',         pattern: 0, palette: 19, seed: 2718, inverted: false },
  { id: 'hills-mint-d',         name: 'Dark Mint Hills',        pattern: 0, palette: 20, seed: 2718, inverted: false },
  { id: 'hills-cherry-d',       name: 'Dark Cherry Hills',    pattern: 0, palette: 21, seed: 2718, inverted: false },
  { id: 'hills-volcano-d',      name: 'Dark Volcano Hills',       pattern: 0, palette: 22, seed: 2718, inverted: false },
  { id: 'hills-indigo-d',       name: 'Dark Indigo Hills',       pattern: 0, palette: 23, seed: 2718, inverted: false },

  // ── Ondas (pattern 1) — seed 3141 ── Light
  { id: 'wave-fire',            name: 'Fire Wave',            pattern: 1, palette: 4,  seed: 3141, inverted: true },
  { id: 'wave-purple',          name: 'Purple Wave',            pattern: 1, palette: 5,  seed: 3141, inverted: true },
  { id: 'wave-toxic',           name: 'Toxic Wave',          pattern: 1, palette: 6,  seed: 3141, inverted: true,  featured: true},
  { id: 'wave-neon',            name: 'Neon Wave',            pattern: 1, palette: 8,  seed: 3141, inverted: true },
  { id: 'wave-cosmic',          name: 'Cosmic Wave',         pattern: 1, palette: 11, seed: 3141, inverted: true },
  { id: 'wave-blue',            name: 'Blue Wave',            pattern: 1, palette: 2,  seed: 3141, inverted: true },
  { id: 'wave-forest',          name: 'Forest Wave',        pattern: 1, palette: 10, seed: 3141, inverted: true },
  { id: 'wave-amber',           name: 'Amber Wave',           pattern: 1, palette: 7,  seed: 3141, inverted: true },
  { id: 'wave-solar',           name: 'Solar Wave',           pattern: 1, palette: 9,  seed: 3141, inverted: true },
  { id: 'wave-sunrise',         name: 'Sunrise Wave',       pattern: 1, palette: 3,  seed: 3141, inverted: true },
  { id: 'wave-charcoal',        name: 'Charcoal Wave',          pattern: 1, palette: 0,  seed: 3141, inverted: true },
  { id: 'wave-stone',           name: 'Stone Wave',           pattern: 1, palette: 1,  seed: 3141, inverted: true },
  { id: 'wave-ocean',           name: 'Ocean Wave',          pattern: 1, palette: 12, seed: 3141, inverted: true },
  { id: 'wave-blood',           name: 'Blood Wave',          pattern: 1, palette: 13, seed: 3141, inverted: true },
  { id: 'wave-sunset',          name: 'Sunset Wave',      pattern: 1, palette: 14, seed: 3141, inverted: true },
  { id: 'wave-emerald',         name: 'Emerald Wave',       pattern: 1, palette: 15, seed: 3141, inverted: true },
  { id: 'wave-cyberpunk',       name: 'Cyberpunk Wave',       pattern: 1, palette: 16, seed: 3141, inverted: true },
  { id: 'wave-sands',           name: 'Sands Wave',          pattern: 1, palette: 17, seed: 3141, inverted: true },
  { id: 'wave-lavender',        name: 'Lavender Wave',         pattern: 1, palette: 18, seed: 3141, inverted: true },
  { id: 'wave-gold',            name: 'Gold Wave',            pattern: 1, palette: 19, seed: 3141, inverted: true },
  { id: 'wave-mint',            name: 'Mint Wave',           pattern: 1, palette: 20, seed: 3141, inverted: true },
  { id: 'wave-cherry',          name: 'Cherry Wave',       pattern: 1, palette: 21, seed: 3141, inverted: true },
  { id: 'wave-volcano',         name: 'Volcano Wave',          pattern: 1, palette: 22, seed: 3141, inverted: true },
  { id: 'wave-indigo',          name: 'Indigo Wave',          pattern: 1, palette: 23, seed: 3141, inverted: true },
  // Dark
  { id: 'wave-fire-d',          name: 'Dark Fire Wave',            pattern: 1, palette: 4,  seed: 3141, inverted: false },
  { id: 'wave-purple-d',        name: 'Dark Purple Wave',            pattern: 1, palette: 5,  seed: 3141, inverted: false },
  { id: 'wave-toxic-d',         name: 'Dark Toxic Wave',          pattern: 1, palette: 6,  seed: 3141, inverted: false },
  { id: 'wave-neon-d',          name: 'Dark Neon Wave',            pattern: 1, palette: 8,  seed: 3141, inverted: false },
  { id: 'wave-cosmic-d',        name: 'Dark Cosmic Wave',         pattern: 1, palette: 11, seed: 3141, inverted: false },
  { id: 'wave-blue-d',          name: 'Dark Blue Wave',            pattern: 1, palette: 2,  seed: 3141, inverted: false },
  { id: 'wave-forest-d',        name: 'Dark Forest Wave',        pattern: 1, palette: 10, seed: 3141, inverted: false },
  { id: 'wave-amber-d',         name: 'Dark Amber Wave',           pattern: 1, palette: 7,  seed: 3141, inverted: false },
  { id: 'wave-solar-d',         name: 'Dark Solar Wave',           pattern: 1, palette: 9,  seed: 3141, inverted: false },
  { id: 'wave-sunrise-d',       name: 'Dark Sunrise Wave',       pattern: 1, palette: 3,  seed: 3141, inverted: false },
  { id: 'wave-charcoal-d',      name: 'Dark Charcoal Wave',          pattern: 1, palette: 0,  seed: 3141, inverted: false },
  { id: 'wave-stone-d',         name: 'Dark Stone Wave',           pattern: 1, palette: 1,  seed: 3141, inverted: false },
  { id: 'wave-ocean-d',         name: 'Dark Ocean Wave',          pattern: 1, palette: 12, seed: 3141, inverted: false },
  { id: 'wave-blood-d',         name: 'Dark Blood Wave',          pattern: 1, palette: 13, seed: 3141, inverted: false },
  { id: 'wave-sunset-d',        name: 'Dark Sunset Wave',      pattern: 1, palette: 14, seed: 3141, inverted: false },
  { id: 'wave-emerald-d',       name: 'Dark Emerald Wave',       pattern: 1, palette: 15, seed: 3141, inverted: false },
  { id: 'wave-cyberpunk-d',     name: 'Dark Cyberpunk Wave',       pattern: 1, palette: 16, seed: 3141, inverted: false },
  { id: 'wave-sands-d',         name: 'Dark Sands Wave',          pattern: 1, palette: 17, seed: 3141, inverted: false },
  { id: 'wave-lavender-d',      name: 'Dark Lavender Wave',         pattern: 1, palette: 18, seed: 3141, inverted: false },
  { id: 'wave-gold-d',          name: 'Dark Gold Wave',            pattern: 1, palette: 19, seed: 3141, inverted: false },
  { id: 'wave-mint-d',          name: 'Dark Mint Wave',           pattern: 1, palette: 20, seed: 3141, inverted: false },
  { id: 'wave-cherry-d',        name: 'Dark Cherry Wave',       pattern: 1, palette: 21, seed: 3141, inverted: false },
  { id: 'wave-volcano-d',       name: 'Dark Volcano Wave',          pattern: 1, palette: 22, seed: 3141, inverted: false },
  { id: 'wave-indigo-d',        name: 'Dark Indigo Wave',          pattern: 1, palette: 23, seed: 3141, inverted: false },

  // ── Montanhas (pattern 3) — seed 1618 ── Light
  { id: 'peaks-fire',           name: 'Fire Peaks',       pattern: 3, palette: 4,  seed: 1618, inverted: true },
  { id: 'peaks-purple',         name: 'Purple Peaks',       pattern: 3, palette: 5,  seed: 1618, inverted: true },
  { id: 'peaks-toxic',          name: 'Toxic Peaks',     pattern: 3, palette: 6,  seed: 1618, inverted: true },
  { id: 'peaks-neon',           name: 'Neon Peaks',       pattern: 3, palette: 8,  seed: 1618, inverted: true },
  { id: 'peaks-cosmic',         name: 'Cosmic Peaks',    pattern: 3, palette: 11, seed: 1618, inverted: true },
  { id: 'peaks-blue',           name: 'Blue Peaks',       pattern: 3, palette: 2,  seed: 1618, inverted: true },
  { id: 'peaks-forest',         name: 'Forest Peaks',   pattern: 3, palette: 10, seed: 1618, inverted: true },
  { id: 'peaks-amber',          name: 'Amber Peaks',      pattern: 3, palette: 7,  seed: 1618, inverted: true },
  { id: 'peaks-solar',          name: 'Solar Peaks',      pattern: 3, palette: 9,  seed: 1618, inverted: true },
  { id: 'peaks-sunrise',        name: 'Sunrise Peaks',  pattern: 3, palette: 3,  seed: 1618, inverted: true },
  { id: 'peaks-charcoal',       name: 'Charcoal Peaks',     pattern: 3, palette: 0,  seed: 1618, inverted: true },
  { id: 'peaks-stone',          name: 'Stone Peaks',      pattern: 3, palette: 1,  seed: 1618, inverted: true },
  { id: 'peaks-ocean',          name: 'Ocean Peaks',     pattern: 3, palette: 12, seed: 1618, inverted: true },
  { id: 'peaks-blood',          name: 'Blood Peaks',     pattern: 3, palette: 13, seed: 1618, inverted: true },
  { id: 'peaks-sunset',         name: 'Sunset Peaks',  pattern: 3, palette: 14, seed: 1618, inverted: true },
  { id: 'peaks-emerald',        name: 'Emerald Peaks',   pattern: 3, palette: 15, seed: 1618, inverted: true },
  { id: 'peaks-cyberpunk',      name: 'Cyberpunk Peaks',   pattern: 3, palette: 16, seed: 1618, inverted: true },
  { id: 'peaks-sands',          name: 'Sands Peaks',      pattern: 3, palette: 17, seed: 1618, inverted: true },
  { id: 'peaks-lavender',       name: 'Lavender Peaks',     pattern: 3, palette: 18, seed: 1618, inverted: true },
  { id: 'peaks-gold',           name: 'Gold Peaks',        pattern: 3, palette: 19, seed: 1618, inverted: true },
  { id: 'peaks-mint',           name: 'Mint Peaks',       pattern: 3, palette: 20, seed: 1618, inverted: true },
  { id: 'peaks-cherry',         name: 'Cherry Peaks',   pattern: 3, palette: 21, seed: 1618, inverted: true },
  { id: 'peaks-volcano',        name: 'Volcano Peaks',      pattern: 3, palette: 22, seed: 1618, inverted: true },
  { id: 'peaks-indigo',         name: 'Indigo Peaks',      pattern: 3, palette: 23, seed: 1618, inverted: true },
  // Dark
  { id: 'peaks-fire-d',         name: 'Dark Fire Peaks',       pattern: 3, palette: 4,  seed: 1618, inverted: false },
  { id: 'peaks-purple-d',       name: 'Dark Purple Peaks',       pattern: 3, palette: 5,  seed: 1618, inverted: false },
  { id: 'peaks-toxic-d',        name: 'Dark Toxic Peaks',     pattern: 3, palette: 6,  seed: 1618, inverted: false },
  { id: 'peaks-neon-d',         name: 'Dark Neon Peaks',       pattern: 3, palette: 8,  seed: 1618, inverted: false },
  { id: 'peaks-cosmic-d',       name: 'Dark Cosmic Peaks',    pattern: 3, palette: 11, seed: 1618, inverted: false },
  { id: 'peaks-blue-d',         name: 'Dark Blue Peaks',       pattern: 3, palette: 2,  seed: 1618, inverted: false },
  { id: 'peaks-forest-d',       name: 'Dark Forest Peaks',   pattern: 3, palette: 10, seed: 1618, inverted: false },
  { id: 'peaks-amber-d',        name: 'Dark Amber Peaks',      pattern: 3, palette: 7,  seed: 1618, inverted: false },
  { id: 'peaks-solar-d',        name: 'Dark Solar Peaks',      pattern: 3, palette: 9,  seed: 1618, inverted: false },
  { id: 'peaks-sunrise-d',      name: 'Dark Sunrise Peaks',  pattern: 3, palette: 3,  seed: 1618, inverted: false },
  { id: 'peaks-charcoal-d',     name: 'Dark Charcoal Peaks',     pattern: 3, palette: 0,  seed: 1618, inverted: false },
  { id: 'peaks-stone-d',        name: 'Dark Stone Peaks',      pattern: 3, palette: 1,  seed: 1618, inverted: false },
  { id: 'peaks-ocean-d',        name: 'Dark Ocean Peaks',     pattern: 3, palette: 12, seed: 1618, inverted: false },
  { id: 'peaks-blood-d',        name: 'Dark Blood Peaks',     pattern: 3, palette: 13, seed: 1618, inverted: false },
  { id: 'peaks-sunset-d',       name: 'Dark Sunset Peaks', pattern: 3, palette: 14, seed: 1618, inverted: false },
  { id: 'peaks-emerald-d',      name: 'Dark Emerald Peaks',  pattern: 3, palette: 15, seed: 1618, inverted: false },
  { id: 'peaks-cyberpunk-d',    name: 'Dark Cyberpunk Peaks',  pattern: 3, palette: 16, seed: 1618, inverted: false },
  { id: 'peaks-sands-d',        name: 'Dark Sands Peaks',     pattern: 3, palette: 17, seed: 1618, inverted: false },
  { id: 'peaks-lavender-d',     name: 'Dark Lavender Peaks',    pattern: 3, palette: 18, seed: 1618, inverted: false },
  { id: 'peaks-gold-d',         name: 'Dark Gold Peaks',       pattern: 3, palette: 19, seed: 1618, inverted: false },
  { id: 'peaks-mint-d',         name: 'Dark Mint Peaks',      pattern: 3, palette: 20, seed: 1618, inverted: false },
  { id: 'peaks-cherry-d',       name: 'Dark Cherry Peaks',  pattern: 3, palette: 21, seed: 1618, inverted: false },
  { id: 'peaks-volcano-d',      name: 'Dark Volcano Peaks',     pattern: 3, palette: 22, seed: 1618, inverted: false },
  { id: 'peaks-indigo-d',       name: 'Dark Indigo Peaks',     pattern: 3, palette: 23, seed: 1618, inverted: false },

  // ── Arcos (pattern 4) — seed 4669 ── Light
  { id: 'arcs-fire',            name: 'Fire Arcs',           pattern: 4, palette: 4,  seed: 4669, inverted: true },
  { id: 'arcs-purple',          name: 'Purple Arcs',           pattern: 4, palette: 5,  seed: 4669, inverted: true },
  { id: 'arcs-toxic',           name: 'Toxic Arcs',         pattern: 4, palette: 6,  seed: 4669, inverted: true },
  { id: 'arcs-neon',            name: 'Neon Arcs',           pattern: 4, palette: 8,  seed: 4669, inverted: true },
  { id: 'arcs-cosmic',          name: 'Cosmic Arcs',        pattern: 4, palette: 11, seed: 4669, inverted: true },
  { id: 'arcs-blue',            name: 'Blue Arcs',           pattern: 4, palette: 2,  seed: 4669, inverted: true },
  { id: 'arcs-forest',          name: 'Forest Arcs',       pattern: 4, palette: 10, seed: 4669, inverted: true },
  { id: 'arcs-amber',           name: 'Amber Arcs',          pattern: 4, palette: 7,  seed: 4669, inverted: true },
  { id: 'arcs-solar',           name: 'Solar Arcs',          pattern: 4, palette: 9,  seed: 4669, inverted: true },
  { id: 'arcs-sunrise',         name: 'Sunrise Arcs',      pattern: 4, palette: 3,  seed: 4669, inverted: true },
  { id: 'arcs-charcoal',        name: 'Charcoal Arcs',         pattern: 4, palette: 0,  seed: 4669, inverted: true },
  { id: 'arcs-stone',           name: 'Stone Arcs',          pattern: 4, palette: 1,  seed: 4669, inverted: true },
  { id: 'arcs-ocean',           name: 'Ocean Arcs',         pattern: 4, palette: 12, seed: 4669, inverted: true },
  { id: 'arcs-blood',           name: 'Blood Arcs',         pattern: 4, palette: 13, seed: 4669, inverted: true },
  { id: 'arcs-sunset',          name: 'Sunset Arcs',     pattern: 4, palette: 14, seed: 4669, inverted: true },
  { id: 'arcs-emerald',         name: 'Emerald Arcs',      pattern: 4, palette: 15, seed: 4669, inverted: true },
  { id: 'arcs-cyberpunk',       name: 'Cyberpunk Arcs',      pattern: 4, palette: 16, seed: 4669, inverted: true },
  { id: 'arcs-sands',           name: 'Sands Arcs',         pattern: 4, palette: 17, seed: 4669, inverted: true },
  { id: 'arcs-lavender',        name: 'Lavender Arcs',        pattern: 4, palette: 18, seed: 4669, inverted: true },
  { id: 'arcs-gold',            name: 'Gold Arcs',           pattern: 4, palette: 19, seed: 4669, inverted: true },
  { id: 'arcs-mint',            name: 'Mint Arcs',          pattern: 4, palette: 20, seed: 4669, inverted: true },
  { id: 'arcs-cherry',          name: 'Cherry Arcs',      pattern: 4, palette: 21, seed: 4669, inverted: true },
  { id: 'arcs-volcano',         name: 'Volcano Arcs',         pattern: 4, palette: 22, seed: 4669, inverted: true },
  { id: 'arcs-indigo',          name: 'Indigo Arcs',         pattern: 4, palette: 23, seed: 4669, inverted: true },
  // Dark
  { id: 'arcs-fire-d',          name: 'Dark Fire Arcs',           pattern: 4, palette: 4,  seed: 4669, inverted: false },
  { id: 'arcs-purple-d',        name: 'Dark Purple Arcs',           pattern: 4, palette: 5,  seed: 4669, inverted: false },
  { id: 'arcs-toxic-d',         name: 'Dark Toxic Arcs',         pattern: 4, palette: 6,  seed: 4669, inverted: false },
  { id: 'arcs-neon-d',          name: 'Dark Neon Arcs',           pattern: 4, palette: 8,  seed: 4669, inverted: false },
  { id: 'arcs-cosmic-d',        name: 'Dark Cosmic Arcs',        pattern: 4, palette: 11, seed: 4669, inverted: false },
  { id: 'arcs-blue-d',          name: 'Dark Blue Arcs',           pattern: 4, palette: 2,  seed: 4669, inverted: false },
  { id: 'arcs-forest-d',        name: 'Dark Forest Arcs',       pattern: 4, palette: 10, seed: 4669, inverted: false },
  { id: 'arcs-amber-d',         name: 'Dark Amber Arcs',          pattern: 4, palette: 7,  seed: 4669, inverted: false },
  { id: 'arcs-solar-d',         name: 'Dark Solar Arcs',          pattern: 4, palette: 9,  seed: 4669, inverted: false },
  { id: 'arcs-sunrise-d',       name: 'Dark Sunrise Arcs',      pattern: 4, palette: 3,  seed: 4669, inverted: false },
  { id: 'arcs-charcoal-d',      name: 'Dark Charcoal Arcs',         pattern: 4, palette: 0,  seed: 4669, inverted: false },
  { id: 'arcs-stone-d',         name: 'Dark Stone Arcs',          pattern: 4, palette: 1,  seed: 4669, inverted: false },
  { id: 'arcs-ocean-d',         name: 'Dark Ocean Arcs',         pattern: 4, palette: 12, seed: 4669, inverted: false },
  { id: 'arcs-blood-d',         name: 'Dark Blood Arcs',         pattern: 4, palette: 13, seed: 4669, inverted: false },
  { id: 'arcs-sunset-d',        name: 'Dark Sunset Arcs',     pattern: 4, palette: 14, seed: 4669, inverted: false },
  { id: 'arcs-emerald-d',       name: 'Dark Emerald Arcs',      pattern: 4, palette: 15, seed: 4669, inverted: false },
  { id: 'arcs-cyberpunk-d',     name: 'Dark Cyberpunk Arcs',      pattern: 4, palette: 16, seed: 4669, inverted: false },
  { id: 'arcs-sands-d',         name: 'Dark Sands Arcs',         pattern: 4, palette: 17, seed: 4669, inverted: false },
  { id: 'arcs-lavender-d',      name: 'Dark Lavender Arcs',        pattern: 4, palette: 18, seed: 4669, inverted: false },
  { id: 'arcs-gold-d',          name: 'Dark Gold Arcs',           pattern: 4, palette: 19, seed: 4669, inverted: false },
  { id: 'arcs-mint-d',          name: 'Dark Mint Arcs',          pattern: 4, palette: 20, seed: 4669, inverted: false },
  { id: 'arcs-cherry-d',        name: 'Dark Cherry Arcs',      pattern: 4, palette: 21, seed: 4669, inverted: false },
  { id: 'arcs-volcano-d',       name: 'Dark Volcano Arcs',         pattern: 4, palette: 22, seed: 4669, inverted: false },
  { id: 'arcs-indigo-d',        name: 'Dark Indigo Arcs',         pattern: 4, palette: 23, seed: 4669, inverted: false },

  // ── Dunas (pattern 2) — seed 5772 ── Light
  { id: 'dunes-fire',           name: 'Fire Dunes',           pattern: 2, palette: 4,  seed: 5772, inverted: true },
  { id: 'dunes-purple',         name: 'Purple Dunes',           pattern: 2, palette: 5,  seed: 5772, inverted: true },
  { id: 'dunes-toxic',          name: 'Toxic Dunes',         pattern: 2, palette: 6,  seed: 5772, inverted: true },
  { id: 'dunes-neon',           name: 'Neon Dunes',           pattern: 2, palette: 8,  seed: 5772, inverted: true },
  { id: 'dunes-cosmic',         name: 'Cosmic Dunes',        pattern: 2, palette: 11, seed: 5772, inverted: true },
  { id: 'dunes-blue',           name: 'Blue Dunes',           pattern: 2, palette: 2,  seed: 5772, inverted: true },
  { id: 'dunes-forest',         name: 'Forest Dunes',       pattern: 2, palette: 10, seed: 5772, inverted: true },
  { id: 'dunes-amber',          name: 'Amber Dunes',          pattern: 2, palette: 7,  seed: 5772, inverted: true },
  { id: 'dunes-solar',          name: 'Solar Dunes',          pattern: 2, palette: 9,  seed: 5772, inverted: true },
  { id: 'dunes-sunrise',        name: 'Sunrise Dunes',      pattern: 2, palette: 3,  seed: 5772, inverted: true },
  { id: 'dunes-charcoal',       name: 'Charcoal Dunes',         pattern: 2, palette: 0,  seed: 5772, inverted: true },
  { id: 'dunes-stone',          name: 'Stone Dunes',          pattern: 2, palette: 1,  seed: 5772, inverted: true },
  { id: 'dunes-ocean',          name: 'Ocean Dunes',         pattern: 2, palette: 12, seed: 5772, inverted: true },
  { id: 'dunes-blood',          name: 'Blood Dunes',         pattern: 2, palette: 13, seed: 5772, inverted: true },
  { id: 'dunes-sunset',         name: 'Sunset Dunes',     pattern: 2, palette: 14, seed: 5772, inverted: true },
  { id: 'dunes-emerald',        name: 'Emerald Dunes',      pattern: 2, palette: 15, seed: 5772, inverted: true },
  { id: 'dunes-cyberpunk',      name: 'Cyberpunk Dunes',      pattern: 2, palette: 16, seed: 5772, inverted: true },
  { id: 'dunes-sands',          name: 'Sands Dunes',         pattern: 2, palette: 17, seed: 5772, inverted: true },
  { id: 'dunes-lavender',       name: 'Lavender Dunes',        pattern: 2, palette: 18, seed: 5772, inverted: true },
  { id: 'dunes-gold',           name: 'Gold Dunes',           pattern: 2, palette: 19, seed: 5772, inverted: true },
  { id: 'dunes-mint',           name: 'Mint Dunes',          pattern: 2, palette: 20, seed: 5772, inverted: true },
  { id: 'dunes-cherry',         name: 'Cherry Dunes',      pattern: 2, palette: 21, seed: 5772, inverted: true },
  { id: 'dunes-volcano',        name: 'Volcano Dunes',         pattern: 2, palette: 22, seed: 5772, inverted: true },
  { id: 'dunes-indigo',         name: 'Indigo Dunes',         pattern: 2, palette: 23, seed: 5772, inverted: true },
  // Dark
  { id: 'dunes-fire-d',         name: 'Dark Fire Dunes',           pattern: 2, palette: 4,  seed: 5772, inverted: false },
  { id: 'dunes-purple-d',       name: 'Dark Purple Dunes',           pattern: 2, palette: 5,  seed: 5772, inverted: false },
  { id: 'dunes-toxic-d',        name: 'Dark Toxic Dunes',         pattern: 2, palette: 6,  seed: 5772, inverted: false },
  { id: 'dunes-neon-d',         name: 'Dark Neon Dunes',           pattern: 2, palette: 8,  seed: 5772, inverted: false },
  { id: 'dunes-cosmic-d',       name: 'Dark Cosmic Dunes',        pattern: 2, palette: 11, seed: 5772, inverted: false },
  { id: 'dunes-blue-d',         name: 'Dark Blue Dunes',           pattern: 2, palette: 2,  seed: 5772, inverted: false },
  { id: 'dunes-forest-d',       name: 'Dark Forest Dunes',       pattern: 2, palette: 10, seed: 5772, inverted: false },
  { id: 'dunes-amber-d',        name: 'Dark Amber Dunes',          pattern: 2, palette: 7,  seed: 5772, inverted: false },
  { id: 'dunes-solar-d',        name: 'Dark Solar Dunes',          pattern: 2, palette: 9,  seed: 5772, inverted: false },
  { id: 'dunes-sunrise-d',      name: 'Dark Sunrise Dunes',      pattern: 2, palette: 3,  seed: 5772, inverted: false },
  { id: 'dunes-charcoal-d',     name: 'Dark Charcoal Dunes',         pattern: 2, palette: 0,  seed: 5772, inverted: false },
  { id: 'dunes-stone-d',        name: 'Dark Stone Dunes',          pattern: 2, palette: 1,  seed: 5772, inverted: false },
  { id: 'dunes-ocean-d',        name: 'Dark Ocean Dunes',         pattern: 2, palette: 12, seed: 5772, inverted: false },
  { id: 'dunes-blood-d',        name: 'Dark Blood Dunes',         pattern: 2, palette: 13, seed: 5772, inverted: false },
  { id: 'dunes-sunset-d',       name: 'Dark Sunset Dunes',     pattern: 2, palette: 14, seed: 5772, inverted: false },
  { id: 'dunes-emerald-d',      name: 'Dark Emerald Dunes',      pattern: 2, palette: 15, seed: 5772, inverted: false },
  { id: 'dunes-cyberpunk-d',    name: 'Dark Cyberpunk Dunes',      pattern: 2, palette: 16, seed: 5772, inverted: false },
  { id: 'dunes-sands-d',        name: 'Dark Sands Dunes',         pattern: 2, palette: 17, seed: 5772, inverted: false },
  { id: 'dunes-lavender-d',     name: 'Dark Lavender Dunes',        pattern: 2, palette: 18, seed: 5772, inverted: false },
  { id: 'dunes-gold-d',         name: 'Dark Gold Dunes',           pattern: 2, palette: 19, seed: 5772, inverted: false },
  { id: 'dunes-mint-d',         name: 'Dark Mint Dunes',          pattern: 2, palette: 20, seed: 5772, inverted: false },
  { id: 'dunes-cherry-d',       name: 'Dark Cherry Dunes',      pattern: 2, palette: 21, seed: 5772, inverted: false },
  { id: 'dunes-volcano-d',      name: 'Dark Volcano Dunes',         pattern: 2, palette: 22, seed: 5772, inverted: false },
  { id: 'dunes-indigo-d',       name: 'Dark Indigo Dunes',         pattern: 2, palette: 23, seed: 5772, inverted: false },

  // ── Deserto (pattern 5) — seed 8811 ── Light
  { id: 'desert-fire',          name: 'Fire Desert',         pattern: 5, palette: 4,  seed: 8811, inverted: true },
  { id: 'desert-purple',        name: 'Purple Desert',         pattern: 5, palette: 5,  seed: 8811, inverted: true },
  { id: 'desert-toxic',         name: 'Toxic Desert',       pattern: 5, palette: 6,  seed: 8811, inverted: true },
  { id: 'desert-neon',          name: 'Neon Desert',         pattern: 5, palette: 8,  seed: 8811, inverted: true },
  { id: 'desert-cosmic',        name: 'Cosmic Desert',      pattern: 5, palette: 11, seed: 8811, inverted: true },
  { id: 'desert-blue',          name: 'Blue Desert',         pattern: 5, palette: 2,  seed: 8811, inverted: true },
  { id: 'desert-forest',        name: 'Forest Desert',     pattern: 5, palette: 10, seed: 8811, inverted: true },
  { id: 'desert-amber',         name: 'Amber Desert',        pattern: 5, palette: 7,  seed: 8811, inverted: true },
  { id: 'desert-solar',         name: 'Solar Desert',        pattern: 5, palette: 9,  seed: 8811, inverted: true },
  { id: 'desert-sunrise',       name: 'Sunrise Desert',    pattern: 5, palette: 3,  seed: 8811, inverted: true },
  { id: 'desert-charcoal',      name: 'Charcoal Desert',       pattern: 5, palette: 0,  seed: 8811, inverted: true },
  { id: 'desert-stone',         name: 'Stone Desert',        pattern: 5, palette: 1,  seed: 8811, inverted: true },
  { id: 'desert-ocean',         name: 'Ocean Desert',       pattern: 5, palette: 12, seed: 8811, inverted: true },
  { id: 'desert-blood',         name: 'Blood Desert',       pattern: 5, palette: 13, seed: 8811, inverted: true },
  { id: 'desert-sunset',        name: 'Sunset Desert',    pattern: 5, palette: 14, seed: 8811, inverted: true },
  { id: 'desert-emerald',       name: 'Emerald Desert',     pattern: 5, palette: 15, seed: 8811, inverted: true },
  { id: 'desert-cyberpunk',     name: 'Cyberpunk Desert',     pattern: 5, palette: 16, seed: 8811, inverted: true },
  { id: 'desert-sands',         name: 'Sands Desert',        pattern: 5, palette: 17, seed: 8811, inverted: true },
  { id: 'desert-lavender',      name: 'Lavender Desert',       pattern: 5, palette: 18, seed: 8811, inverted: true },
  { id: 'desert-gold',          name: 'Gold Desert',          pattern: 5, palette: 19, seed: 8811, inverted: true },
  { id: 'desert-mint',          name: 'Mint Desert',         pattern: 5, palette: 20, seed: 8811, inverted: true },
  { id: 'desert-cherry',        name: 'Cherry Desert',     pattern: 5, palette: 21, seed: 8811, inverted: true },
  { id: 'desert-volcano',       name: 'Volcano Desert',        pattern: 5, palette: 22, seed: 8811, inverted: true },
  { id: 'desert-indigo',        name: 'Indigo Desert',        pattern: 5, palette: 23, seed: 8811, inverted: true },
  // Dark
  { id: 'desert-fire-d',        name: 'Dark Fire Desert',         pattern: 5, palette: 4,  seed: 8811, inverted: false },
  { id: 'desert-purple-d',      name: 'Dark Purple Desert',         pattern: 5, palette: 5,  seed: 8811, inverted: false },
  { id: 'desert-toxic-d',       name: 'Dark Toxic Desert',       pattern: 5, palette: 6,  seed: 8811, inverted: false },
  { id: 'desert-neon-d',        name: 'Dark Neon Desert',         pattern: 5, palette: 8,  seed: 8811, inverted: false },
  { id: 'desert-cosmic-d',      name: 'Dark Cosmic Desert',      pattern: 5, palette: 11, seed: 8811, inverted: false },
  { id: 'desert-blue-d',        name: 'Dark Blue Desert',         pattern: 5, palette: 2,  seed: 8811, inverted: false },
  { id: 'desert-forest-d',      name: 'Dark Forest Desert',     pattern: 5, palette: 10, seed: 8811, inverted: false },
  { id: 'desert-amber-d',       name: 'Dark Amber Desert',        pattern: 5, palette: 7,  seed: 8811, inverted: false },
  { id: 'desert-solar-d',       name: 'Dark Solar Desert',        pattern: 5, palette: 9,  seed: 8811, inverted: false },
  { id: 'desert-sunrise-d',     name: 'Dark Sunrise Desert',    pattern: 5, palette: 3,  seed: 8811, inverted: false },
  { id: 'desert-charcoal-d',    name: 'Dark Charcoal Desert',       pattern: 5, palette: 0,  seed: 8811, inverted: false },
  { id: 'desert-stone-d',       name: 'Dark Stone Desert',        pattern: 5, palette: 1,  seed: 8811, inverted: false },
  { id: 'desert-ocean-d',       name: 'Dark Ocean Desert',       pattern: 5, palette: 12, seed: 8811, inverted: false },
  { id: 'desert-blood-d',       name: 'Dark Blood Desert',       pattern: 5, palette: 13, seed: 8811, inverted: false },
  { id: 'desert-sunset-d',      name: 'Dark Sunset Desert',   pattern: 5, palette: 14, seed: 8811, inverted: false },
  { id: 'desert-emerald-d',     name: 'Dark Emerald Desert',    pattern: 5, palette: 15, seed: 8811, inverted: false },
  { id: 'desert-cyberpunk-d',   name: 'Dark Cyberpunk Desert',    pattern: 5, palette: 16, seed: 8811, inverted: false },
  { id: 'desert-sands-d',       name: 'Dark Sands Desert',       pattern: 5, palette: 17, seed: 8811, inverted: false },
  { id: 'desert-lavender-d',    name: 'Dark Lavender Desert',      pattern: 5, palette: 18, seed: 8811, inverted: false },
  { id: 'desert-gold-d',        name: 'Dark Gold Desert',         pattern: 5, palette: 19, seed: 8811, inverted: false },
  { id: 'desert-mint-d',        name: 'Dark Mint Desert',        pattern: 5, palette: 20, seed: 8811, inverted: false },
  { id: 'desert-cherry-d',      name: 'Dark Cherry Desert',    pattern: 5, palette: 21, seed: 8811, inverted: false },
  { id: 'desert-volcano-d',     name: 'Dark Volcano Desert',       pattern: 5, palette: 22, seed: 8811, inverted: false },
  { id: 'desert-indigo-d',      name: 'Dark Indigo Desert',       pattern: 5, palette: 23, seed: 8811, inverted: false },

  // ── Big Sur Waves (pattern 8) ──
  { id: 'bigsur-aurora',        name: 'Aurora Big Sur',        pattern: 8, palette: 15, seed: 1234, inverted: true },
  { id: 'bigsur-cosmic',        name: 'Cosmic Big Sur',        pattern: 8, palette: 11, seed: 5678, inverted: true },
  { id: 'bigsur-indigo-d',      name: 'Dark Indigo Big Sur',   pattern: 8, palette: 23, seed: 1234, inverted: false },
  { id: 'bigsur-sunset-d',      name: 'Dark Sunset Big Sur',   pattern: 8, palette: 14, seed: 5678, inverted: false },

  // ── Monterey Silk (pattern 9) ──
  { id: 'monterey-lavender',    name: 'Lavender Monterey',    pattern: 9, palette: 18, seed: 4321, inverted: true },
  { id: 'monterey-neon',        name: 'Neon Monterey',        pattern: 9, palette: 8,  seed: 8765, inverted: true },
  { id: 'monterey-cyber-d',     name: 'Dark Cyberpunk Monterey', pattern: 9, palette: 16, seed: 4321, inverted: false },
  { id: 'monterey-midnight-d',  name: 'Dark Midnight Monterey', pattern: 9, palette: 5,  seed: 8765, inverted: false },

  // ── Ventura Petals (pattern 10) ──
  { id: 'ventura-solar',        name: 'Solar Ventura',        pattern: 10, palette: 9,  seed: 1122, inverted: true },
  { id: 'ventura-cherry',       name: 'Cherry Ventura',       pattern: 10, palette: 21, seed: 3344, inverted: true },
  { id: 'ventura-fire-d',       name: 'Dark Fire Ventura',     pattern: 10, palette: 4,  seed: 1122, inverted: false },
  { id: 'ventura-toxic-d',      name: 'Dark Toxic Ventura',    pattern: 10, palette: 6,  seed: 3344, inverted: false },

  // ── Sonoma Topo (pattern 11) ──
  { id: 'sonoma-sands',         name: 'Sands Sonoma',         pattern: 11, palette: 17, seed: 9988, inverted: true },
  { id: 'sonoma-emerald',       name: 'Emerald Sonoma',       pattern: 11, palette: 15, seed: 7766, inverted: true },
  { id: 'sonoma-charcoal-d',     name: 'Dark Charcoal Sonoma',  pattern: 11, palette: 0,  seed: 9988, inverted: false },
  { id: 'sonoma-stone-d',        name: 'Dark Stone Sonoma',     pattern: 11, palette: 1,  seed: 7766, inverted: false },

  // ── Mesh Gradient (pattern 12) ──
  { id: 'mesh-aurora',          name: 'Aurora Mesh',          pattern: 12, palette: 15, seed: 5555, inverted: true },
  { id: 'mesh-cyber',           name: 'Cyberpunk Mesh',       pattern: 12, palette: 16, seed: 6666, inverted: true },
  { id: 'mesh-midnight-d',      name: 'Dark Midnight Mesh',   pattern: 12, palette: 5,  seed: 5555, inverted: false },
  { id: 'mesh-volcano-d',       name: 'Dark Volcano Mesh',    pattern: 12, palette: 22, seed: 6666, inverted: false },

  // ── Glass Bubbles (pattern 13) ──
  { id: 'bubbles-blue',         name: 'Blue Bubbles',         pattern: 13, palette: 2,  seed: 1212, inverted: true },
  { id: 'bubbles-mint',         name: 'Mint Bubbles',         pattern: 13, palette: 20, seed: 3434, inverted: true },
  { id: 'bubbles-indigo-d',     name: 'Dark Indigo Bubbles',  pattern: 13, palette: 23, seed: 1212, inverted: false },
  { id: 'bubbles-forest-d',     name: 'Dark Forest Bubbles',  pattern: 13, palette: 10, seed: 3434, inverted: false },

  // ── Light Beams (pattern 14) ──
  { id: 'beams-neon',           name: 'Neon Beams',           pattern: 14, palette: 8,  seed: 9090, inverted: true },
  { id: 'beams-cosmic',         name: 'Cosmic Beams',         pattern: 14, palette: 11, seed: 8080, inverted: true },
  { id: 'beams-charcoal-d',     name: 'Dark Charcoal Beams',  pattern: 14, palette: 0,  seed: 9090, inverted: false },
  { id: 'beams-fire-d',         name: 'Dark Fire Beams',      pattern: 14, palette: 4,  seed: 8080, inverted: false },

  // ── Origami Crystal (pattern 15) ──
  { id: 'origami-amber',        name: 'Amber Origami',        pattern: 15, palette: 7,  seed: 2020, inverted: true },
  { id: 'origami-cherry',       name: 'Cherry Origami',       pattern: 15, palette: 21, seed: 4040, inverted: true },
  { id: 'origami-stone-d',       name: 'Dark Stone Origami',    pattern: 15, palette: 1,  seed: 2020, inverted: false },
  { id: 'origami-blood-d',       name: 'Dark Blood Origami',    pattern: 15, palette: 13, seed: 4040, inverted: false },

  // ── Minimalist Lines (pattern 16) ──
  { id: 'lines-sunrise',        name: 'Sunrise Lines',        pattern: 16, palette: 3,  seed: 7070, inverted: true },
  { id: 'lines-ocean',          name: 'Ocean Lines',          pattern: 16, palette: 12, seed: 6060, inverted: true },
  { id: 'lines-lavender-d',     name: 'Dark Lavender Lines',  pattern: 16, palette: 18, seed: 7070, inverted: false },
  { id: 'lines-gold-d',         name: 'Dark Gold Lines',      pattern: 16, palette: 19, seed: 6060, inverted: false },

  // ── Aurora Lights (pattern 17) ──
  { id: 'aurora-nordic',        name: 'Nordic Aurora',        pattern: 17, palette: 26, seed: 1111, inverted: true },
  { id: 'aurora-pastel',        name: 'Pastel Aurora',        pattern: 17, palette: 24, seed: 2222, inverted: true },
  { id: 'aurora-retro-d',       name: 'Dark Retro Aurora',    pattern: 17, palette: 27, seed: 3333, inverted: false },
  { id: 'aurora-cyber-d',       name: 'Dark Cyber Aurora',    pattern: 17, palette: 28, seed: 4444, inverted: false },

  // ── Cyber Grid (pattern 18) ──
  { id: 'grid-miami',           name: 'Miami Grid',           pattern: 18, palette: 31, seed: 5555, inverted: true },
  { id: 'grid-gold',            name: 'Golden Grid',          pattern: 18, palette: 25, seed: 6666, inverted: true },
  { id: 'grid-cyber-d',         name: 'Dark Cyber Grid',      pattern: 18, palette: 28, seed: 7777, inverted: false },
  { id: 'grid-synth-d',         name: 'Dark Synth Grid',      pattern: 18, palette: 27, seed: 8888, inverted: false },

  // ── Liquid Marble (pattern 19) ──
  { id: 'marble-candy',         name: 'Cotton Candy Marble',  pattern: 19, palette: 32, seed: 9999, inverted: true },
  { id: 'marble-emerald',       name: 'Emerald Sea Marble',   pattern: 19, palette: 33, seed: 1010, inverted: true },
  { id: 'marble-sunset-d',      name: 'Dark Sunset Marble',   pattern: 19, palette: 30, seed: 2020, inverted: false },
  { id: 'marble-holo-d',        name: 'Dark Holographic Marble', pattern: 19, palette: 29, seed: 3030, inverted: false }
];

export function getWallpaper(id) {
  return wallpapers.find(w => w.id === id);
}

export function getFeatured() {
  return wallpapers.find(w => w.featured) || wallpapers[0];
}
